### ISSUE TITLE
Victini Sprite Sheet Conversion Issue in aseriestodis

### ISSUE THREAD

**Issue by ultima-soul** [Gamer2020/DisassemblyConversionTools#1]
The Victini spritesheet from here: https://www.pokecommunity.com/showthread.php?t=336945 
(Direct link: https://www.dropbox.com/sh/y5aq3omupcjl0v8/AACd2sjGLhJHvKQS2jgch-SLa/Fire%20Red/GenV?dl=0&preview=578.png)
has an issue being converted as seen here: https://media.discordapp.net/attachments/419213663107416088/469336651253022739/578_still_front_pic.png

Since your tool uses Wichu's tools for sprite handling, I decided to test out Wichu's Advanced Pokemon Sprite Editor. Sure enough, the same behaviour is seen if you Import All and then select the sprite sheet.

An interesting thing though is if you do Import All, then select only the normal front sprite and Import the sheet, the pixel goes away! This is a really strange quirk between this sprite sheet and Wichu's tool.

Hopefully, you may find if there are any problems in sprite sheet handling in Wichu's code.

Thank you.

**Comment by Gamer2020** [comment]
Pull requests are always welcome!

**Comment by LOuroboros** [comment]
I found a similar issue while I tried to convert a 256x64 sheet with Monferno's sprites.
Look at the flame in Monferno's back sprite's tail.
Left: **[Original Sprite](https://pasteboard.co/HzuHFUK.png)** | Right: Aseriestodis
![untitled](https://user-images.githubusercontent.com/4485172/44236556-bbe5fe00-a183-11e8-8299-bec067d99bfd.PNG)

**Comment by Gamer2020** [comment]
Issue is in the source image. Those pixels are a different color.

https://i.imgur.com/UKB4NWJ.png
