### ISSUE TITLE
Some sheets are converted to Emerald style sheets and put into anim_front_pics, but some others aren't

### ISSUE THREAD

**Issue by LOuroboros** [Gamer2020/DisassemblyConversionTools#2]
Well, basically the title.
I'm slowly making a resource for Pokeruby users, and I noticed that some of the sheets I've converted _(not all of them, just certain ones)_ have been converted to Emerald-styled sheets _(64x128 with 2 frames)_ while some other sprites haven't.

For example, I converted sheets with Turtwig, Grotle and Torterra's sprites, but they're not present in the anim_front_pics folder for some reason.
![explorer-2018-08-16_20-31-12](https://user-images.githubusercontent.com/4485172/44240317-e3dd5d80-a193-11e8-9d67-b0501650c9e6.png)

**Comment by Gamer2020** [comment]
Pull requests are always welcome!

Get Outlook for Android

________________________________

**Comment by Gamer2020** [comment]
I don't see any source images so I am unable to test. Most likely the source images are not the right dimensions.

**Comment by LOuroboros** [comment]
The sprite sheets [b]do have[/b] the correct dimensions _(256x64)_ and they were took from [ChaosRush's 64x64 Sprites Thread in PokeCommunity](http://www.pokecommunity.com/showthread.php?t=267728).
